export const GET_RECIPE = 'GET_RECIPE';
export const SELECT_RECIPE = 'SELECT_RECIPE';
export const ADD_RECIPE = 'ADD_RECIPE';
export const DELETE_SELECTED_RECIPE = 'DELETE_SELECTED_RECIPE';
export const EDIT_SELECTED_RECIPE = 'EDIT_SELECTED_RECIPE';
